# golangci-lint 配置文件
run:
  # 超时时间
  timeout: 5m
  
  # 是否检查测试文件
  tests: true
  
  # 排除要检查的目录
  issues.exclude-dirs:
    - testdata
    - vendor
    - third_party

# 启用的检查器
linters:
  enable:
    - errcheck      # 检查未处理的错误
    - gosimple      # 简化代码建议
    - govet         # Go 官方检查工具
    - ineffassign   # 检测无效赋值
    - staticcheck   # 静态分析
    - unused        # 检测未使用的代码
    - gofmt         # 格式化检查
    - goimports     # import 排序检查
    - gosec         # 安全性检查
    - misspell      # 拼写检查
    - structcheck   # 检测未使用的结构体字段
    - varcheck      # 检测未使用的全局变量
    - deadcode      # 检测无用代码
    - typecheck     # 类型检查
    - nakedret      # 检测裸返回
    - unconvert     # 检测不必要的类型转换
    - gocyclo       # 复杂度检查
    - dupl          # 代码重复检查
    - bodyclose     # 检查 HTTP 响应体是否关闭
    - scopelint     # 检测变量作用域问题
    - exportloopref # 检测循环引用问题
    - goconst      # 检测常量
    - lll          # 行长度检查
    - prealloc     # 检测切片预分配
    - funlen       # 函数长度检查
    - exhaustivestruct # 检查结构体字面量是否完整
    - nestif       # 检测嵌套的 if 语句
    - whitespace   # 检查多余的空白
    - unparam      # 检测未使用的函数参数


# 检查器设置
linters-settings:
  errcheck:
    # 不允许用 _ 忽略错误
    check-blank: true
  
  goimports:
    # 设置你的模块路径，用于 import 分组
    # 请替换成你的实际模块路径
    local-prefixes: github.com/kyson/e-shop-native


# 问题报告设置
issues:
  # 不使用默认的排除规则
  exclude-use-default: false
  
  # 每个 linter 最多报告多少问题（0 = 无限制）
  max-issues-per-linter: 0
  
  # 相同问题最多报告多少次（0 = 无限制）
  max-same-issues: 0
  
  # 排除特定文件的检查
  # exclude-rules:
  #   - path: _test\.go
  #     linters:
  #       - errcheck
