// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kyson/e-shop-native/internal/user-srv/biz"
	"github.com/kyson/e-shop-native/internal/user-srv/conf"
	"github.com/kyson/e-shop-native/internal/user-srv/data"
	"github.com/kyson/e-shop-native/internal/user-srv/service"
	"github.com/kyson/e-shop-native/internal/user-srv/sever"
)

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	bootstrap, err := LoadConfig()
	if err != nil {
		return nil, nil, err
	}
	server := provideServerConfig(bootstrap)
	confData := provideDataConfig(bootstrap)
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userService := biz.NewUserUsecase(userRepo)
	userServiceServer := service.NewUserService(userService)
	grpcServer := sever.NewGRPCServer(server, userServiceServer)
	httpServer := sever.NewHTTPServer(server)
	app := NewApp(grpcServer, httpServer, server, bootstrap)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func provideServerConfig(c *conf.Bootstrap) *conf.Server {
	return c.Server
}

func provideDataConfig(c *conf.Bootstrap) *conf.Data {
	return c.Data
}
