// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kyson/e-shop-native/internal/user-srv/biz"
	"github.com/kyson/e-shop-native/internal/user-srv/conf"
	"github.com/kyson/e-shop-native/internal/user-srv/data"
	"github.com/kyson/e-shop-native/internal/user-srv/service"
	"github.com/kyson/e-shop-native/internal/user-srv/sever"
)

// Injectors from wire.go:

func InitializeApp(s *conf.Server, d *conf.Data) (*App, func(), error) {
	dataData, cleanup, err := data.NewData(d)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userService := biz.NewUserUsecase(userRepo)
	userServiceServer := service.NewUserService(userService)
	server := sever.NewGRPCServer(s, userServiceServer)
	httpServer := sever.NewHTTPServer(s)
	app := NewApp(server, httpServer, s)
	return app, func() {
		cleanup()
	}, nil
}
