// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.0
// source: api/protobuf/user/v1/error_code.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	// 默认值，不指定错误
	ErrorCode_UNKNOWN ErrorCode = 0
	// 内部错误
	ErrorCode_INTERNAL ErrorCode = 1
	// -- 用户服务错误 (1000-1999) --
	ErrorCode_USER_NOT_FOUND        ErrorCode = 1001
	ErrorCode_PASSWORD_INCORRECT    ErrorCode = 1002
	ErrorCode_USER_ALREADY_EXISTS   ErrorCode = 1003
	ErrorCode_USERNAME_FORMAT_ERROR ErrorCode = 1004
	ErrorCode_EMAIL_FORMAT_ERROR    ErrorCode = 1005
	ErrorCode_PHONE_FORMAT_ERROR    ErrorCode = 1006
	ErrorCode_PASSWORD_FORMAT_ERROR ErrorCode = 1007
	// -- 认证服务错误 (2000-2999) --
	ErrorCode_TOKEN_INVALID ErrorCode = 2001
	ErrorCode_TOKEN_EXPIRED ErrorCode = 2002
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "UNKNOWN",
		1:    "INTERNAL",
		1001: "USER_NOT_FOUND",
		1002: "PASSWORD_INCORRECT",
		1003: "USER_ALREADY_EXISTS",
		1004: "USERNAME_FORMAT_ERROR",
		1005: "EMAIL_FORMAT_ERROR",
		1006: "PHONE_FORMAT_ERROR",
		1007: "PASSWORD_FORMAT_ERROR",
		2001: "TOKEN_INVALID",
		2002: "TOKEN_EXPIRED",
	}
	ErrorCode_value = map[string]int32{
		"UNKNOWN":               0,
		"INTERNAL":              1,
		"USER_NOT_FOUND":        1001,
		"PASSWORD_INCORRECT":    1002,
		"USER_ALREADY_EXISTS":   1003,
		"USERNAME_FORMAT_ERROR": 1004,
		"EMAIL_FORMAT_ERROR":    1005,
		"PHONE_FORMAT_ERROR":    1006,
		"PASSWORD_FORMAT_ERROR": 1007,
		"TOKEN_INVALID":         2001,
		"TOKEN_EXPIRED":         2002,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protobuf_user_v1_error_code_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_protobuf_user_v1_error_code_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_protobuf_user_v1_error_code_proto_rawDescGZIP(), []int{0}
}

var File_api_protobuf_user_v1_error_code_proto protoreflect.FileDescriptor

const file_api_protobuf_user_v1_error_code_proto_rawDesc = "" +
	"\n" +
	"%api/protobuf/user/v1/error_code.proto\x12\rapi.common.v1*\x80\x02\n" +
	"\tErrorCode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bINTERNAL\x10\x01\x12\x13\n" +
	"\x0eUSER_NOT_FOUND\x10\xe9\a\x12\x17\n" +
	"\x12PASSWORD_INCORRECT\x10\xea\a\x12\x18\n" +
	"\x13USER_ALREADY_EXISTS\x10\xeb\a\x12\x1a\n" +
	"\x15USERNAME_FORMAT_ERROR\x10\xec\a\x12\x17\n" +
	"\x12EMAIL_FORMAT_ERROR\x10\xed\a\x12\x17\n" +
	"\x12PHONE_FORMAT_ERROR\x10\xee\a\x12\x1a\n" +
	"\x15PASSWORD_FORMAT_ERROR\x10\xef\a\x12\x12\n" +
	"\rTOKEN_INVALID\x10\xd1\x0f\x12\x12\n" +
	"\rTOKEN_EXPIRED\x10\xd2\x0fBBZ@github.com/your-username/e-shop-native/api/protobuf/common/v1;v1b\x06proto3"

var (
	file_api_protobuf_user_v1_error_code_proto_rawDescOnce sync.Once
	file_api_protobuf_user_v1_error_code_proto_rawDescData []byte
)

func file_api_protobuf_user_v1_error_code_proto_rawDescGZIP() []byte {
	file_api_protobuf_user_v1_error_code_proto_rawDescOnce.Do(func() {
		file_api_protobuf_user_v1_error_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protobuf_user_v1_error_code_proto_rawDesc), len(file_api_protobuf_user_v1_error_code_proto_rawDesc)))
	})
	return file_api_protobuf_user_v1_error_code_proto_rawDescData
}

var file_api_protobuf_user_v1_error_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_protobuf_user_v1_error_code_proto_goTypes = []any{
	(ErrorCode)(0), // 0: api.common.v1.ErrorCode
}
var file_api_protobuf_user_v1_error_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protobuf_user_v1_error_code_proto_init() }
func file_api_protobuf_user_v1_error_code_proto_init() {
	if File_api_protobuf_user_v1_error_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protobuf_user_v1_error_code_proto_rawDesc), len(file_api_protobuf_user_v1_error_code_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protobuf_user_v1_error_code_proto_goTypes,
		DependencyIndexes: file_api_protobuf_user_v1_error_code_proto_depIdxs,
		EnumInfos:         file_api_protobuf_user_v1_error_code_proto_enumTypes,
	}.Build()
	File_api_protobuf_user_v1_error_code_proto = out.File
	file_api_protobuf_user_v1_error_code_proto_goTypes = nil
	file_api_protobuf_user_v1_error_code_proto_depIdxs = nil
}
