// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.0
// source: api/protobuf/user/v1/error.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserErr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserErr) Reset() {
	*x = UserErr{}
	mi := &file_api_protobuf_user_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserErr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserErr) ProtoMessage() {}

func (x *UserErr) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_user_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserErr.ProtoReflect.Descriptor instead.
func (*UserErr) Descriptor() ([]byte, []int) {
	return file_api_protobuf_user_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *UserErr) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserErr) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_protobuf_user_v1_error_proto protoreflect.FileDescriptor

const file_api_protobuf_user_v1_error_proto_rawDesc = "" +
	"\n" +
	" api/protobuf/user/v1/error.proto\x12\auser.v1\"7\n" +
	"\aUserErr\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB1Z/github.com/kyson/e-shop/api/protobuf/user/v1;v1b\x06proto3"

var (
	file_api_protobuf_user_v1_error_proto_rawDescOnce sync.Once
	file_api_protobuf_user_v1_error_proto_rawDescData []byte
)

func file_api_protobuf_user_v1_error_proto_rawDescGZIP() []byte {
	file_api_protobuf_user_v1_error_proto_rawDescOnce.Do(func() {
		file_api_protobuf_user_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protobuf_user_v1_error_proto_rawDesc), len(file_api_protobuf_user_v1_error_proto_rawDesc)))
	})
	return file_api_protobuf_user_v1_error_proto_rawDescData
}

var file_api_protobuf_user_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_protobuf_user_v1_error_proto_goTypes = []any{
	(*UserErr)(nil), // 0: user.v1.UserErr
}
var file_api_protobuf_user_v1_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protobuf_user_v1_error_proto_init() }
func file_api_protobuf_user_v1_error_proto_init() {
	if File_api_protobuf_user_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protobuf_user_v1_error_proto_rawDesc), len(file_api_protobuf_user_v1_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protobuf_user_v1_error_proto_goTypes,
		DependencyIndexes: file_api_protobuf_user_v1_error_proto_depIdxs,
		MessageInfos:      file_api_protobuf_user_v1_error_proto_msgTypes,
	}.Build()
	File_api_protobuf_user_v1_error_proto = out.File
	file_api_protobuf_user_v1_error_proto_goTypes = nil
	file_api_protobuf_user_v1_error_proto_depIdxs = nil
}
